export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const EDIT_POST_CHANGE_FIELD = "EDIT_POST_CHANGE_FIELD";
export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE";
export const EDIT_POST_CANCEL = "EDIT_POST_CANCEL";
export const EDIT_EXISTING_POST = "EDIT_EXISTING_POST";

export const REMOVE_POST_FIRST = "REMOVE_MEMO_FIRST";
export const REMOVE_POST_CANCEL = "REMOVE_MEMO_CANCEL";
export const REMOVE_POST_BY_ID = "REMOVE_POST_BY_ID";
export const REMOVE_POST_REQUEST = "REMOVE_POST_REQUEST";
export const REMOVE_POST_SUCCESS = "REMOVE_POST_SUCCESS";
export const REMOVE_POST_ERROR = "REMOVE_POST_ERROR";

export const ADD_TO_TOTAL_SUM = "ADD_TO_TOTAL_SUM";
export const SUBTRACT_FROM_TOTAL_SUM = "SUBTRACT_FROM_TOTAL_SUM";
export const CHANGE_TOTAL_SUM = "CHANGE_TOTAL_SUM";

export const SHOW_DESCRIPTION_REQUEST = "SHOW_DESCRIPTION_REQUEST";
export const SHOW_DESCRIPTION_SUCCESS = "SHOW_DESCRIPTION_SUCCESS";
export const SHOW_DESCRIPTION_FAILURE = "SHOW_DESCRIPTION_FAILURE";
